# Site settings
title: TechFM
email: info@techfm.net.au
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://techfm.net.au" # the base hostname & protocol for your site

phone: 1300 TECHFM
phone_alt: 1300 832436

# Build settings
markdown: kramdown
